# Generated by Django 4.2.4 on 2023-08-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
